# Generated by Django 3.1 on 2020-08-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zipCode', models.IntegerField(null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('userStatus', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=100)),
                ('userRole', models.CharField(default='Trainee', max_length=100)),
                ('enrolledCarriers', models.TextField(max_length=3000, null=True)),
                ('ndaNca', models.FileField(upload_to='ndaNnca')),
                ('costPerMile', models.IntegerField(null=True)),
                ('mc_number', models.IntegerField(null=True)),
                ('dot_number', models.IntegerField(null=True)),
                ('willing_states', models.TextField(max_length=1000, null=True)),
                ('carrier_status', models.CharField(max_length=100, null=True)),
                ('factoring_company', models.CharField(max_length=100, null=True)),
                ('factoring_phone', models.IntegerField(null=True)),
                ('mc_upload', models.FileField(null=True, upload_to='mc')),
                ('w9_upload', models.FileField(null=True, upload_to='w9')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('truck_number', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('max_weight', models.IntegerField(null=True)),
                ('license_plate_number', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMSTruck.account')),
            ],
        ),
        migrations.CreateModel(
            name='AssignLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage_name', models.CharField(max_length=300, null=True)),
                ('broker_name', models.CharField(max_length=300, null=True)),
                ('broker_address', models.CharField(max_length=300, null=True)),
                ('pickupAddress', models.CharField(max_length=300, null=True)),
                ('distance', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('stops', models.IntegerField(null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pickupDate', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_paid', models.BooleanField(default=False, null=True)),
                ('broker_phone', models.IntegerField(null=True)),
                ('broker_email', models.EmailField(max_length=100, null=True)),
                ('load_number', models.IntegerField(null=True)),
                ('dropOffDate', models.DateField(null=True)),
                ('dropOffAddress', models.CharField(max_length=10000, null=True)),
                ('first_available_pickup', models.DateField(null=True)),
                ('rate_confirmation', models.FileField(blank=True, upload_to='load_attachments/rate_confirmation')),
                ('bill_of_landing', models.FileField(blank=True, upload_to=models.CharField(max_length=300, null=True))),
                ('special_comments', models.TextField(max_length=10000, null=True)),
                ('assignToCarrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMSTruck.account')),
            ],
        ),
    ]
