# Generated by Django 3.1 on 2020-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('mc_number', models.IntegerField(null=True)),
                ('dot_number', models.IntegerField(null=True)),
                ('factoring_phone', models.IntegerField(null=True)),
                ('willing_states', models.TextField(max_length=1000, null=True)),
                ('carrier_status', models.CharField(max_length=100, null=True)),
                ('factoring_company', models.CharField(max_length=100, null=True)),
                ('mc_upload', models.FileField(null=True, upload_to='mc')),
                ('costPerMile', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='carrier_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
        migrations.RemoveField(
            model_name='account',
            name='costPerMile',
        ),
        migrations.RemoveField(
            model_name='account',
            name='dot_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='factoring_company',
        ),
        migrations.RemoveField(
            model_name='account',
            name='factoring_phone',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mc_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mc_upload',
        ),
        migrations.RemoveField(
            model_name='account',
            name='willing_states',
        ),
    ]
