# Generated by Django 3.1 on 2020-08-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0002_auto_20200825_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignload',
            name='assignToCarrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMSTruck.carrier'),
        ),
    ]
