# Generated by Django 3.1 on 2020-08-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0004_remove_account_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignload',
            name='final_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
