# Generated by Django 3.1 on 2020-08-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0005_assignload_final_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignload',
            name='final_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
