# Generated by Django 3.1 on 2020-08-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0006_auto_20200826_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignload',
            name='is_awaiting',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
