# Generated by Django 3.1 on 2020-08-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0008_carrier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignload',
            name='dropOffDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignload',
            name='first_available_pickup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignload',
            name='pickupDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
