# Generated by Django 3.1 on 2020-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0009_auto_20200826_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignload',
            name='is_awb',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
