# Generated by Django 3.1 on 2020-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0010_assignload_is_awb'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
