# Generated by Django 3.1 on 2020-08-27 14:39

import TMSTruck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0011_carrier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ndaNca',
            field=models.FileField(upload_to=models.CharField(max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='assignload',
            name='assigned_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignload',
            name='bill_of_landing',
            field=models.FileField(blank=True, upload_to=TMSTruck.models.bill_path),
        ),
        migrations.AlterField(
            model_name='assignload',
            name='rate_confirmation',
            field=models.FileField(blank=True, upload_to=TMSTruck.models.rate_confirmation_path),
        ),
    ]
