# Generated by Django 3.1 on 2020-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0012_auto_20200827_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignload',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignload',
            name='dropOffDate',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='assignload',
            name='first_available_pickup',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='assignload',
            name='pickupDate',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
