# Generated by Django 3.1 on 2020-08-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0014_account_commissionrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TMSTruck.account'),
        ),
    ]
