# Generated by Django 3.1 on 2020-08-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0015_carrier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMSTruck.account'),
        ),
    ]
