# Generated by Django 3.1 on 2020-08-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0016_auto_20200827_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMSTruck.carrier'),
        ),
    ]
