# Generated by Django 3.1 on 2020-08-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0017_auto_20200828_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TMSTruck.account'),
        ),
    ]
