# Generated by Django 3.1 on 2020-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0019_auto_20200831_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='enrolledCarriers',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='userRole',
            field=models.CharField(choices=[('Trainee', 'Trainee'), ('Logistics Manager', 'Logistics Manager'), ('Accounting', 'Accounting'), ('Hiring Manager', 'Hiring Manager'), ('Admin', 'Admin')], default='Trainee', max_length=100, null=True),
        ),
    ]
