# Generated by Django 3.1 on 2020-08-31 15:19

import TMSTruck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0020_auto_20200831_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='insurance',
            field=models.FileField(null=True, upload_to=TMSTruck.models.carrierMcFiles),
        ),
        migrations.AddField(
            model_name='carrier',
            name='w9_upload',
            field=models.FileField(null=True, upload_to=TMSTruck.models.carrierMcFiles),
        ),
        migrations.AlterField(
            model_name='account',
            name='userRole',
            field=models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Logistics Manager', 'Logistics Manager'), ('Accounting', 'Accounting'), ('Hiring Manager', 'Hiring Manager'), ('Admin', 'Admin')], default='Trainee', max_length=100, null=True),
        ),
    ]
