# Generated by Django 3.1 on 2020-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0022_assignload_is_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='commissionRate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
