# Generated by Django 3.1 on 2020-08-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSTruck', '0023_auto_20200901_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='factoring_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
